### ISSUE TITLE
Assessment results

### ISSUE THREAD

**Issue by damwhit** [nicolegooden/mod_0_skills#1]
@nicolegooden  really nice work on this! It's clear you have a good grasp of the OOP concepts we've gone over in mod 0. Great job following proper conventions. You're also naming your methods in a way where it's very clear to me what attribute they're going to affect and how. Keep up the good work moving forward!

Something to think about moving forward: How could you change your Menu class to have a dishes array, that is made up of objects (js data type) with name and price attributes?

**Comment by nicolegooden** [comment]
@damwhit Thank you for this feedback!  I've enjoyed the OOP concepts so far, especially since they require so much precision (really makes me think).  

I've made an attempt at your suggestion for the Menu class.  Please check out this repl and let me know what you think!

[https://repl.it/join/mbieboia-nicolegooden](url)

**Comment by nicolegooden** [comment]
@damwhit Here is my second attempt, where I experimented with creating the array of objects rather than strings:

https://repl.it/join/lsarldul-nicolegooden

**Comment by damwhit** [comment]
Looks good! The only thing I would update is the name of the class. I think MenuItem might be more appropriate in this case

**Comment by nicolegooden** [comment]
@damwhit 

Got it, I updated it in the repl.  Thanks!
